language: python
python:
  - "3.6"

# Bionic is required for nested virtualization.
dist: bionic

stages:
  - before_install

env:
  global:
    - ANSIBLE_VERSION=2.9

before_install:
  # This stage is used to setup the environment to deploy the infrastructure.
  # This will install:
  # - Ansible
  # - Terraform
  # - Terraform Provider for Libvirt
  # - Libvirt
  # - Python dependencies

  # Install Ansible 2.9
  - pip install ansible==$ANSIBLE_VERSION

  # Install Terraform 0.12
  - curl -sLo /tmp/terraform.zip https://releases.hashicorp.com/terraform/0.12.0-rc1/terraform_0.12.0-rc1_linux_amd64.zip
  - unzip /tmp/terraform.zip -d /tmp
  - mv /tmp/terraform ~/bin
  - export PATH="~/bin:$PATH"

  # Install Terraform Provider for Libvirt 0.6.2
  - mkdir -p .terraform.d/plugins
  - curl -sLo terraform-provider-libvirt.tar.gz https://github.com/dmacvicar/terraform-provider-libvirt/releases/download/v0.6.2/terraform-provider-libvirt-0.6.2+git.1585292411.8cbe9ad0.Ubuntu_18.04.amd64.tar.gz
  - tar zxvf terraform-provider-libvirt.tar.gz
  - mv terraform-provider-libvirt .terraform.d/plugins/

  # Install KVM and enable hardware acceleration.
#  - travis_retry sudo -E apt-get -yq --no-install-suggests --no-install-recommends install bridge-utils libpulse0 libvirt-bin qemu-kvm virtinst ubuntu-vm-builder
#  - sudo adduser $USER libvirt
#  - sudo adduser $USER kvm
