language: python
python:
  - "3.6"

# Bionic is required for nested virtualization.
dist: bionic

stages:
  - before_install
  - install

env:
  global:
    - ANSIBLE_VERSION=2.9
    - TERRAFORM_VERSION=0.12.0

before_install:
  # This stage is used to setup the environment to deploy the infrastructure.
  # This will install:
  # - Ansible
  # - Terraform
  # - Terraform Provider for Libvirt
  # - Libvirt

  # Install Ansible 2.9
  - pip install ansible=="$ANSIBLE_VERSION"

  # Install Terraform 0.12
  - curl -sLo /tmp/terraform.zip https://releases.hashicorp.com/terraform/"$TERRAFORM_VERSION"/terraform_"$TERRAFORM_VERSION"_linux_amd64.zip
  - unzip /tmp/terraform.zip -d /tmp
  - sudo mv /tmp/terraform /usr/local/bin

  # Install Terraform Provider for Libvirt 0.6.2
  - mkdir -p .terraform.d/plugins
  - curl -sLo terraform-provider-libvirt.tar.gz https://github.com/dmacvicar/terraform-provider-libvirt/releases/download/v0.6.2/terraform-provider-libvirt-0.6.2+git.1585292411.8cbe9ad0.Ubuntu_18.04.amd64.tar.gz
  - tar zxvf terraform-provider-libvirt.tar.gz
  - mv terraform-provider-libvirt .terraform.d/plugins/

  # Install KVM and enable hardware acceleration.
  - travis_retry sudo -E apt-get -yq --no-install-suggests --no-install-recommends install bridge-utils libpulse0 libvirt-bin qemu-kvm qemu-utils virtinst ubuntu-vm-builder
  - sudo adduser $USER libvirt
  - sudo adduser $USER kvm

  # Install Packer 1.6.4 to create KVM images.
  - curl -sLo /tmp/packer.zip https://releases.hashicorp.com/packer/1.6.4/packer_1.6.4_linux_amd64.zip
  - unzip /tmp/packer.zip -d /tmp
  - sudo mv /tmp/packer /usr/local/bin
  - sudo ln -s /usr/bin/qemu-system-x86_64 /usr/bin/qemu-kvm
  - mkdir ~/VirtualMachines

  # Create ssh keys
  - ssh-keygen -f ~/.ssh/id_rsa -t rsa -N ''

  # Download Centos 8.2 image
  #- travis_wait curl -sLo ~/VirtualMachines/centos8.iso http://linuxsoft.cern.ch/centos/8.2.2004/isos/x86_64/CentOS-8.2.2004-x86_64-boot.iso
  - travis_wait 30 wget -q http://linuxsoft.cern.ch/centos/8.2.2004/isos/x86_64/CentOS-8.2.2004-x86_64-boot.iso -O ~/VirtualMachines/CentOS-8.2.2004-x86_64-boot.iso

  # Clone packer-terraform-kvm repo
  - git clone https://github.com/89luca89/packer-terraform-kvm
  - sed -i 's/CentOS-8.1.1911-x86_64-dvd1.iso/\/home\/travis\/VirtualMachines\/CentOS-8.2.2004-x86_64-boot.iso/g' packer-terraform-kvm/packer/centos8/centos8.json
  - sed -i 's/3ee3f4ea1538e026fff763e2b284a6f20b259d91d1ad5688f5783a67d279423b/c67876a5602faa17f68b40ccf2628799b87454aa67700f0f57eec15c6ccdd98c/g' packer-terraform-kvm/packer/centos8/centos8.json

install:
  # This stage deploy a basic infrastructure starting from
  # the inventory-example.yml file placed in the root directory
  # of this project.
  - echo $PATH
  - pushd packer-terraform-kvm/packer/centos8 && packer build centos8.json
