language: python
python:
  - "3.6"

# Bionic is required for nested virtualization.
dist: bionic

stages:
  - before_install

env:
  global:
    - ANSIBLE_VERSION=2.9

before_install:
  # This stage is used to setup the environment to deploy the infrastructure.
  # This will install:
  # - Ansible
  # - Terraform
  # - Terraform Provider for Libvirt
  # - Libvirt
  # - Python dependencies

  # Install Ansible 2.9
  - pip install ansible==$ANSIBLE_VERSION

  # Install KVM and enable hardware acceleration.
#  - travis_retry sudo -E apt-get -yq --no-install-suggests --no-install-recommends install bridge-utils libpulse0 libvirt-bin qemu-kvm virtinst ubuntu-vm-builder
#  - sudo adduser $USER libvirt
#  - sudo adduser $USER kvm
