language: python
python:
  - "3.6"

# Bionic is required for nested virtualization.
dist: bionic

stages:
  - before_install
  - install

env:
  global:
    - ANSIBLE_VERSION=2.9
    - TERRAFORM_VERSION=0.12.0

before_install:
  # This stage is used to setup the environment to deploy the infrastructure.
  # This will install:
  # - Ansible
  # - Terraform
  # - Terraform Provider for Libvirt
  # - Libvirt

  # Install Ansible 2.9
  - pip install ansible=="$ANSIBLE_VERSION"

  # Install Terraform 0.12
  - curl -sLo /tmp/terraform.zip https://releases.hashicorp.com/terraform/"$TERRAFORM_VERSION"/terraform_"$TERRAFORM_VERSION"_linux_amd64.zip
  - unzip /tmp/terraform.zip -d /tmp
  - mv /tmp/terraform ~/bin
  - export PATH="~/bin:$PATH"

  # Install Terraform Provider for Libvirt 0.6.2
  - mkdir -p .terraform.d/plugins
  - curl -sLo terraform-provider-libvirt.tar.gz https://github.com/dmacvicar/terraform-provider-libvirt/releases/download/v0.6.2/terraform-provider-libvirt-0.6.2+git.1585292411.8cbe9ad0.Ubuntu_18.04.amd64.tar.gz
  - tar zxvf terraform-provider-libvirt.tar.gz
  - mv terraform-provider-libvirt .terraform.d/plugins/

  # Install KVM and enable hardware acceleration.
  - travis_retry sudo -E apt-get -yq --no-install-suggests --no-install-recommends install bridge-utils libpulse0 libvirt-bin qemu-kvm virtinst ubuntu-vm-builder
  - sudo adduser $USER libvirt
  - sudo adduser $USER kvm

  # Install Packer 1.6.4 to create KVM images.
  - curl -sLo /tmp/packer.zip https://releases.hashicorp.com/packer/1.6.4/packer_1.6.4_linux_amd64.zip
  - unzip /tmp/packer.zip -d /tmp
  - mv /tmp/packer ~/bin
  - mkdir ~/VirtualMachines

  # Create ssh keys
  - ssh-keygen -f ~/.ssh/id_rsa -t rsa -N ''

  # Download Centos 8.2 image
  - travis_wait curl -sLo ~/VirtualMachines/centos8.iso http://linuxsoft.cern.ch/centos/8.2.2004/isos/x86_64/CentOS-8.2.2004-x86_64-boot.iso

  # Clone packer-terraform-kvm repo
  - git clone https://github.com/89luca89/packer-terraform-kvm

install:
  # This stage deploy a basic infrastructure starting from
  # the inventory-example.yml file placed in the root directory
  # of this project.
  - find / -name qemu-kvm
  - pushd packer-terraform-kvm/packer/centos8 && packer build centos8.json
