language: python
python:
  - "3.6"

# Bionic is required for nested virtualization.
dist: bionic

stages:
  - before_install
  - install
  - script

env:
  global:
    - ANSIBLE_VERSION=2.9
    - TERRAFORM_VERSION=0.12.0
    - PACKER_VERSION=1.6.4

before_install:
  # This stage is used to setup the environment to deploy the infrastructure.
  # This will install:
  # - Libvirt
  # - Ansible
  # - Terraform
  # - Terraform Provider for Libvirt

  # Install KVM and enable hardware acceleration.
  - travis_retry sudo -E apt-get -yq --no-install-suggests --no-install-recommends install bridge-utils libpulse0 libvirt-bin qemu-kvm qemu-utils virtinst ubuntu-vm-builder libvirt-daemon
  - sudo adduser $USER libvirt
  - sudo adduser $USER kvm

  # Install Ansible 2.9
  - pip install ansible=="$ANSIBLE_VERSION"
  - pip show ansible
  - ls -la /home/travis/virtualenv/python3.6.10/lib/python3.6/site-packages/
  - find / -name ansible-playbook* 2>/dev/null

#  # Install Terraform 0.12
#  - curl -sLo /tmp/terraform.zip https://releases.hashicorp.com/terraform/"$TERRAFORM_VERSION"/terraform_"$TERRAFORM_VERSION"_linux_amd64.zip
#  - unzip /tmp/terraform.zip -d /tmp
#  - sudo mv /tmp/terraform /usr/local/bin
#
#  # Install Terraform Provider for Libvirt 0.6.2
#  - mkdir -p ~/.terraform.d/plugins/linux_amd64
#  - curl -sLo terraform-provider-libvirt.tar.gz https://github.com/dmacvicar/terraform-provider-libvirt/releases/download/v0.6.2/terraform-provider-libvirt-0.6.2+git.1585292411.8cbe9ad0.Ubuntu_18.04.amd64.tar.gz
#  - tar zxvf terraform-provider-libvirt.tar.gz
#  - mv terraform-provider-libvirt ~/.terraform.d/plugins/linux_amd64/
#  - ~/.terraform.d/plugins/linux_amd64/terraform-provider-libvirt -version 
#
#  # Install other necessary packages
#  - sudo apt-get install sshpass
#
#  # Install python requirements
#  - pip install -r requirements.txt
#
#  # Install Packer 1.6.4 to create KVM images.
#  - curl -sLo /tmp/packer.zip https://releases.hashicorp.com/packer/"$PACKER_VERSION"/packer_"$PACKER_VERSION"_linux_amd64.zip
#  - unzip /tmp/packer.zip -d /tmp
#  - sudo mv /tmp/packer /usr/local/bin
#  - sudo ln -s /usr/bin/qemu-system-x86_64 /usr/bin/qemu-kvm
#  - mkdir ~/VirtualMachines
#
#  # Manage ssh keys to allow Ansible to access root user.
#  - echo "root:password" | sudo chpasswd
#  - ssh-keygen -f ~/.ssh/id_rsa -t rsa -N ''
#  - sshpass -p "password" ssh-copy-id -o StrictHostKeyChecking=no root@127.0.0.1
#
#  # Download Centos 8.2 image
#  - travis_wait 30 wget -q http://linuxsoft.cern.ch/centos/8.2.2004/isos/x86_64/CentOS-8.2.2004-x86_64-boot.iso -O ~/VirtualMachines/CentOS-8.2.2004-x86_64-boot.iso
#
#install:
#  # This stage prepare the Centos8 image template
#  # using Packer.
#
#  # Create qcow2 centos template using Packer
#  - pushd test/packer/centos8 && PACKER_LOG=1 sudo packer build centos8.json && popd
#
#script:
#  # This stage deploy a basic infrastructure starting from
#  # the inventory-test.yml file placed in the test/ directory
#  # of this project.
#
#  # Run ansible-playbook tests
#  # using `sudo -E su $USER -c '...'` we avoid to restart session 
#  # after adding travis user to the libvirt group
#  - sudo -E sudo -u $USER -E bash -c "/usr/bin/ansible-playbook -i test/inventory-test.yml -v -u root main.yml"
#
#notifications:
#  email:
#    - luca.dimaio1@gmail.com
#    - greggialessio@gmail.com
