---
# defaults file for terraform
#

## DEFAULTS FOR VM RESOURCES
cpu: 1
memory: 1024
vm_autostart: False

terraform_version: 0.12

# In case a bastion is specified, we should provide a jump host
# also to ansible to access the VMs via the bastion host.
ansible_ssh_common_args: '-o StrictHostKeyChecking=no {% if ansible_jump_hosts is defined and ansible_jump_hosts is not none %}  -o ProxyCommand="ssh -W %h:%p -o StrictHostKeyChecking=no -q  {% for bastion in ansible_jump_hosts %}{{ bastion.user }}@{{ bastion.host }} -p {{ bastion.port }} {% if not loop.last %} -o ProxyCommand={% for quote in range(loop.index-1) %}\\{% endfor %}\"ssh -W {{ bastion.host }}:{{ bastion.port }} -q {% endif %} {% endfor %}  {% for x in ansible_jump_hosts %}{% for quote in range(loop.revindex)%}{% for q in range(quote) %}\{% endfor %}{% endfor %}"{% endfor %}{% endif %}'

##
base_deploy_path: "{{ lookup('env','HOME') }}"
state_save_file: "{{ ansible_inventory_sources[0] }}-state.tar.gz"

os_family_support:
  - RedHat
  - Suse
  - Debian
  - FreeBSD
  - Alpine

...
