---

galaxy_info:
  author: 89luca89, alegrey91
  description: ansible role to deploy IaC using terraform.
  license: GPL-3.0-only

  min_ansible_version: 2.9

  platforms:
  - name: RedHat
    versions:
    - all
  - name: Suse
    versions:
    - all
  - name: Debian
    versions:
    - all

  galaxy_tags:
    - system
    - qemu
    - kvm
    - libvirt
    - terraform

...
