# Ensure that the os_family variable has been set for current host.
- name: Assert os_family
  assert:
    quiet: yes
    that:
      - "{{ item }}"
    fail_msg: >
      You must specify the os_family for host {{ inventory_hostname }},
      supported values are: {{ os_family_support }}
  with_items:
      - "os_family is defined"
      - "os_family in os_family_support"

# Ensure that the mandatory variables for the host are set.
- name: Assert VMs Variables
  assert:
    quiet: yes
    that: "{{ item }} is defined"
    fail_msg: >
      You must specify {{ item }}
  with_items:
      - hostvars['terraform_node']
      - hostvars['terraform_node']['ansible_host']
      - hostvars['terraform_node']['ansible_connection']
      - ansible_host
      - disk_source
      - pool_name
      - ssh_password
      - ssh_port
      - ssh_public_key_file
      - ssh_user
      - network_interfaces

# Ensure that the mandatory variables for the host are set.
- name: Assert VMs Network Variables - At least one interface is defined
  assert:
    quiet: yes
    that:
      - "{{ network_interfaces.keys() | list | length }} > 0"
    fail_msg: >
      "Declare at least one interface"

# Ensure that the mandatory variables for the host are set.
- name: Assert VMs Network Variables - NAT should be our first interface
  assert:
    quiet: yes
    that:
      - "{{ network_interfaces.values() | list }}[0].type == 'nat'"
    fail_msg: >
      "First interface declared must be NAT type"

# Ensure that the mandatory variables for the host are set.
- name: Assert VMs Network Variables
  assert:
    quiet: yes
    that:
      - "{{ item }}.name is defined"
      - "{{ item }}.type is defined"
      - "{{ item }}.ip is defined"
      - "{{ item }}.gw is defined"
      - "{{ item }}.dns is defined"
    fail_msg: >
      Incomplete interface declaration for {{ item }}, missing a mandatory var
  with_items:
    - "{{ network_interfaces.values() | list }}"

# Ensure that the mandatory variables for the host are set.
- name: Assert VMs Network Type Variables
  assert:
    quiet: yes
    that:
      - "{{ item }}.type == 'nat' or {{ item }}.type == 'macvtap' or {{ item }}.type == 'bridge'"
    fail_msg: >
      Unsupported value for interface type.
  with_items:
    - "{{ network_interfaces.values() | list }}"

# Ensure that the mandatory variables for the host are set.
- name: Assert VMs DNS Network Variables
  assert:
    quiet: yes
    that:
      - "{{ item.dns }} | length > 0"
    fail_msg: >
      Incomplete interface dns specification.
  when:
    - "item.dns is defined"
  with_items:
    - "{{ network_interfaces.values() | list }}"

# If terraform_bastion_enabled is true, we need to ensure that
# all the dependent variables are set in order to function properly.
- name: Assert Bastion Variables
  assert:
    quiet: yes
    that:
      - "{{ item }} is defined"
    fail_msg: >
      You must specify {{ item }} when terraform_bastion_enabled is True
  with_items:
      - ansible_jump_hosts
      - terraform_bastion_host
      - terraform_bastion_password
      - terraform_bastion_port
      - terraform_bastion_user
  when:
    - terraform_bastion_enabled is defined
    - terraform_bastion_enabled

# Include the variables of the os_family of the host.
- include_vars: "vars/os/family/{{ os_family }}.yml"

# Check if we have a public ssh_key file
- name: "Ensure public key ssh file exists"
  stat:
    path: "{{ ssh_public_key_file }}"
  register: ssh_public_key_file_stat
  when:
    - ssh_public_key_file is defined
  delegate_to: terraform_node

# If it exists, read it, it will be deployed in the authorized_keys of
# the newly created hosts to perform the ansible tasks.
- name: "Read public key for ssh"
  set_fact:
    ssh_public_key: "{{ lookup('file', '{{ ssh_public_key_file }}') }}"
  when:
    - ssh_public_key_file_stat.stat.exists
  delegate_to: terraform_node
