---

# main task for terraform role
#
#

- name: Assert os_family
  assert:
    that:
      - "{{ item }}"
    fail_msg: >
      You must specify the os_family for host {{ inventory_hostname }},
      supported values are: {{ os_family_support }}
  with_items:
      - "os_family is defined"
      - "os_family in os_family_support"
  tags: deploy, destroy, apply, provision, generate_hcl

- name: Assert VMs Variables
  assert:
    that: "{{ item }} is defined"
    fail_msg: >
      You must specify {{ item }}
  with_items:
      - ansible_host
      - terraform_bastion_enabled
      - disk_source
      - pool_name
      - provider_uri
      - ssh_password
      - ssh_port
      - ssh_public_key_file
      - ssh_user
  tags: deploy, destroy, apply, provision, generate_hcl

- name: Assert Bastion Variables
  assert:
    that:
      - "{{ item }} is defined"
    fail_msg: >
      You must specify {{ item }} when terraform_bastion_enabled is True
  with_items:
      - ansible_jump_hosts
      - terraform_bastion_host
      - terraform_bastion_password
      - terraform_bastion_port
      - terraform_bastion_user
  when:
    - terraform_bastion_enabled is defined
    - terraform_bastion_enabled
  tags: deploy, destroy, apply, provision, generate_hcl

- include_vars: "vars/os/family/{{ os_family }}.yml"
  tags: deploy, destroy, apply, provision

- include_tasks: deploy_vm.yml
  tags: deploy, destroy, apply, generate_hcl

- name: Wait for system to become reachable
  wait_for_connection:
    delay: 1
    timeout: 300
  tags: provision

- name: gather facts
  setup:
  tags: provision

- include_tasks: post_deploy.yml
  tags: provision
