---

# main task for terraform role
#
#

# Ensure that the os_family variable has been set for current host.
- name: Assert os_family
  assert:
    that:
      - "{{ item }}"
    fail_msg: >
      You must specify the os_family for host {{ inventory_hostname }},
      supported values are: {{ os_family_support }}
  with_items:
      - "os_family is defined"
      - "os_family in os_family_support"
  tags: deploy, destroy, apply, provision, generate_hcl

# Ensure that the mandatory variables for the host are set.
- name: Assert VMs Variables
  assert:
    that: "{{ item }} is defined"
    fail_msg: >
      You must specify {{ item }}
  with_items:
      - ansible_host
      - terraform_bastion_enabled
      - disk_source
      - pool_name
      - provider_uri
      - ssh_password
      - ssh_port
      - ssh_public_key_file
      - ssh_user
  tags: deploy, destroy, apply, provision, generate_hcl

# If terraform_bastion_enabled is true, we need to ensure that
# all the dependent variables are set in order to function properly.
- name: Assert Bastion Variables
  assert:
    that:
      - "{{ item }} is defined"
    fail_msg: >
      You must specify {{ item }} when terraform_bastion_enabled is True
  with_items:
      - ansible_jump_hosts
      - terraform_bastion_host
      - terraform_bastion_password
      - terraform_bastion_port
      - terraform_bastion_user
  when:
    - terraform_bastion_enabled is defined
    - terraform_bastion_enabled
  tags: deploy, destroy, apply, provision, generate_hcl

# Include the variables of the os_family of the host.
- include_vars: "vars/os/family/{{ os_family }}.yml"
  tags: deploy, destroy, apply, provision

# Deploy the HCL files, use Terraform to deploy the infrastructure.
- include_tasks: deploy_vm.yml
  tags: deploy, destroy, apply, generate_hcl

- name: Wait for system to become reachable
  wait_for_connection:
    delay: 1
    timeout: 300
  tags: provision

# Ansible: gather facts of the newly created hosts.
- name: gather facts
  setup:
  tags: provision

# Perform post-deploy tasks, such as users, networks and so on...
- include_tasks: post_deploy.yml
  tags: provision
