---

# main task for terraform role
#
#

# Assert that all variables are well set.
- include_tasks:
    file: assert_vars.yml
    apply:
      tags:
        - always
  tags: always

# Setup all the variables starting from existing ones.
- include_tasks:
    file: setup_vars.yml
    apply:
      tags:
        - always
  tags: always, test

# Deploy the HCL files, use Terraform to deploy the infrastructure.
- include_tasks: deploy_vm.yml
  tags: deploy, destroy, apply, generate_hcl, test

# Perform post-deploy tasks, such as users, networks and so on...
- include_tasks: post_deploy.yml
  tags: provision

# Perform post-deploy tasks, such as users, networks and so on...
- include_tasks: "storage/disk_{{ os_family }}_setup.yml"
  tags: provision
