---

# Post deploy for VMs deployed by terraform.
#

- name: Install Basic Packages
  package:
    name: "{{ base_packages }}"
    state: present
  when: (ansible_os_family == "RedHat") or
        (ansible_os_family == "Debian") or
        (ansible_os_family == "Suse")
  tags: provision

- name: Install Basic Packages
  pkgng:
    name: "{{ base_packages }}"
    state: present
  when: ansible_os_family == "FreeBSD"
  tags: provision

- name: Update systems
  shell: "{{ update_command }}"
  become: true
  tags: provision
