---

# Post deploy for VMs deployed by terraform.
#

# Upgrade systems but limit to only
# security updates, to keep track of
# the packages versions.
- name: Update systems
  shell: "{{ update_command }}"
  become: true
  tags: provision
