---

# Post deploy for VMs deployed by terraform.
#

- name: Set Root password /1
  set_fact:
    ansible_ssh_pass: "{{ set_new_password }}"
  when: set_new_password is defined
  tags: provision

- name: Set Root password /2
  user:
    name: "root"
    update_password: always
    password: "{{ set_new_password | password_hash('sha512', '') }}"
  when: set_new_password is defined
  tags: provision

# Also set a default password for ansible to use.
# if we have a set_new_password variable, set it to this value as
# the new hosts will have the newly setup after the deploy.
# Else default to the ssh_password mantatory value.
- name: "Set ansible_ssh_pass"
  set_fact:
    ansible_ssh_pass: "{% if set_new_password is defined %}{{ set_new_password }}{% else %}{{ ssh_password }}{% endif %}"
  tags: provision

# Upgrade systems but limit to only
# security updates, to keep track of
# the packages versions.
- name: Update systems
  shell: "{{ update_command }}"
  become: true
  tags: provision
