---
# tasks file for terraform
#
#
#
#

- name: "Deploy terraform files - cloudinit"
  template:
    src: cloud_init.yml.j2
    dest: "{{ hcl_deploy_path }}/cloud_init_{{ inventory_hostname }}.yml"
    mode: 0644
  when: cloud_init is defined and cloud_init
  tags: deploy, generate_hcl
  delegate_to: terraform_node

# Deploy the terraform files for each host. Use jinja2 for templating.
- name: "Deploy terraform files - variables"
  template:
    src: variables.tf.j2
    dest: "{{ hcl_deploy_path }}/variables.tf"
    mode: 0644
  register: terraform_variables
  tags: deploy, generate_hcl
  delegate_to: terraform_node

# Deploy the terraform files for each host. Use jinja2 for templating.
- name: "Deploy terraform files - VM"
  template:
    src: terraform-vm.tf.j2
    dest: "{{ hcl_deploy_path }}/{{ inventory_hostname }}.tf"
    mode: 0644
  register: terraform_vm
  tags: deploy, generate_hcl
  delegate_to: terraform_node

- name: "Find hypervisors file tree"
  find:
    path: "{{ terrible_path }}"
    file_type: directory
  register: hypervisors_tf
  tags: deploy, destroy, apply, generate_hcl, purge
  run_once: yes
  delegate_to: terraform_node

# Create an array containing the list of nodes in the form of node-name.j2,...
- name: "Remove unmanaged nodes - generate list of managed files"
  set_fact:
    managed_files: "{{ managed_files | default([]) + [hostvars[item]['hcl_deploy_path'] + '/' + item + '.tf'] }}"
  tags: deploy, generate_hcl
  run_once: yes
  with_items:
    - "{{ play_hosts }}"
  when: full_run
  delegate_to: terraform_node

# Create an array containing the list of files representing the nodes in the folder.
- name: "Remove unmanaged nodes - find all files"
  find:
    paths: "{{ hcl_deploy_path }}/"
    patterns: "*.tf"
  register: nodes_tf
  when: full_run
  tags: deploy, generate_hcl
  delegate_to: terraform_node

# Remove files that are orphan in the inventory.
# This will make terraform remove the nodes that are undefined from
# the inventory.
- name: "Remove unmanaged nodes - delete unmanaged files"
  file:
    path: "{{ item.path }}"
    state: absent
  with_items:
    - "{{ nodes_tf.files | sort(attribute='path') }}"
  when:
    - full_run
    - item.path not in managed_files
    - not "variables.tf" in item.path
  tags: deploy, generate_hcl
  delegate_to: terraform_node

- name: "Terraform renew target VMs"
  set_fact:
    destroy: yes
  tags: never, destroy
  delegate_to: terraform_node

# Perform terraform destroy on specific resources, if state is changed save it
- name: "Terraform shut down target VMs (preserve resources)"  # noqa 503
  terraform:
    project_path: "{{ hcl_deploy_path }}/"
    force_init: yes
    state: absent
    lock: no
    targets: "libvirt_domain.domain_{{ inventory_hostname }}"
  throttle: 1
  tags: deploy, apply, destroy
  register: terraform_shutdown
  when:
    - (destroy is defined and destroy) or (terraform_variables is defined and terraform_variables.changed) or (terraform_vm is defined and terraform_vm.changed)
  delegate_to: terraform_node

# Perform terraform destroy, if state is changed save it
- name: "Terraform destroy VMs and all resources"
  terraform:
    project_path: "{{ item.path }}"
    force_init: yes
    state: absent
  tags: never, purge
  run_once: yes
  register: terraform_destroy
  with_items:
    - "{{ hypervisors_tf.files | sort(attribute='path') }}"
  delegate_to: terraform_node

- name: "Terraform init VMs and all resources"
  terraform:
    project_path: "{{ item.path }}"
    force_init: yes
    state: present
  tags: deploy, apply
  run_once: yes
  check_mode: yes
  with_items:
    - "{{ hypervisors_tf.files | sort(attribute='path') }}"
  delegate_to: terraform_node

# Perform terraform apply, if state is changed  save it
- name: "Terraform apply VMs"
  terraform:
    project_path: "{{ item.path }}"
    state: present
  tags: deploy, apply
  run_once: yes
  with_items:
    - "{{ hypervisors_tf.files | sort(attribute='path') }}"
  register: terraform_command
  delegate_to: terraform_node

### !!! Important
# Here we register the terraform_output that in combination with the
# output provider in the .tf file will return us the DHCP lease IP of
# the NAT network we use as management for the role.
#
# We merge now the results of all hypervisors in a single dictionary to
# lookup after.
- name: "Merge hypervisors results"
  set_fact:
    terraform_output: "{{ terraform_output | default({}) | combine(item.outputs) }}"
  with_items:
    - "{{ terraform_command.results }}"
  tags: deploy, apply
  delegate_to: terraform_node

...
