---

# -----------------------------------------------------------------------------
# State management:
#   Check if we already have a state file, in case unpack it and use it
#   else just continue

- name: Check that a state file exists for current inventory
  stat:
    path: "{{ ansible_inventory_sources[0] }}-state.tar.gz"
  register: inventory_status
  delegate_to: terraform_node

- name: Unpack saved state to "{{ hcl_deploy_path |dirname }}"
  unarchive:
    src: "{{ ansible_inventory_sources[0] }}-state.tar.gz"
    dest: "{{ hcl_deploy_path |dirname }}"
    creates: "{{ hcl_deploy_path }}/.terraform"
    remote_src: yes
    mode: 0755
  run_once: yes
  delegate_to: terraform_node
#
# -----------------------------------------------------------------------------
