---
name: Ansible Run

# on: [push]

on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]

jobs:
  run-all-distros:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    outputs:
      inventories: ${{ steps.output-inventories.outputs.inventories }}
    steps:
      - uses: actions/checkout@v2

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: "just-a-placeholder-so-we-dont-get-errors"

      - name: Adding Known Hosts
        run: ssh-keyscan -p ${{ secrets.SSH_PORT }} -H ${{ secrets.SSH_HOST }} 2>/dev/null >> ~/.ssh/known_hosts

      - name: Deploy folder
        run: |
          ssh -p ${{ secrets.SSH_PORT }} -l ${{ secrets.SSH_USER }} ${{ secrets.SSH_HOST }} "mkdir -p ~/${{ github.sha }}"
          rsync -aH -e "ssh -p ${{ secrets.SSH_PORT }} -l ${{ secrets.SSH_USER }}" ./  ${{ secrets.SSH_HOST }}:~/${{ github.sha }}/

      - name: Alpine
        run: |
          ssh -t -p ${{ secrets.SSH_PORT }} -l ${{ secrets.SSH_USER }} ${{ secrets.SSH_HOST }} <<EOF

            set -e

            export PY_COLORS=1
            export ANSIBLE_FORCE_COLOR=1

            cd ~/${{ github.sha }}

            echo "VALIDATE $DISTRO ******************************************************************"
            echo "ansible-playbook -i examples/inventory-test-${DISTRO}.yml -u root main.yml"
            ansible-playbook -i examples/inventory-test-${DISTRO}.yml -u root main.yml

            echo "!!!SUCCESS!!!"

            echo "Cleanup $DISTRO ******************************************************************"
            echo "ansible-playbook -i examples/inventory-test-${DISTRO}.yml -u root main.yml --tags purge"
            ansible-playbook -i examples/inventory-test-${DISTRO}.yml -u root main.yml --tags purge

          EOF
        env:
          PY_COLORS: "1"
          ANSIBLE_FORCE_COLOR: "1"
          DISTRO: "alpine"

      - name: Centos7
        run: |
          ssh -t -p ${{ secrets.SSH_PORT }} -l ${{ secrets.SSH_USER }} ${{ secrets.SSH_HOST }} <<EOF

            set -e

            export PY_COLORS=1
            export ANSIBLE_FORCE_COLOR=1

            cd ~/${{ github.sha }}

            echo "VALIDATE $DISTRO ******************************************************************"
            echo "ansible-playbook -i examples/inventory-test-${DISTRO}.yml -u root main.yml"
            ansible-playbook -i examples/inventory-test-${DISTRO}.yml -u root main.yml

            echo "!!!SUCCESS!!!"

            echo "Cleanup $DISTRO ******************************************************************"
            echo "ansible-playbook -i examples/inventory-test-${DISTRO}.yml -u root main.yml --tags purge"
            ansible-playbook -i examples/inventory-test-${DISTRO}.yml -u root main.yml --tags purge

          EOF
        env:
          PY_COLORS: "1"
          ANSIBLE_FORCE_COLOR: "1"
          DISTRO: "centos7"

      - name: Centos8
        run: |
          ssh -t -p ${{ secrets.SSH_PORT }} -l ${{ secrets.SSH_USER }} ${{ secrets.SSH_HOST }} <<EOF

            set -e

            export PY_COLORS=1
            export ANSIBLE_FORCE_COLOR=1

            cd ~/${{ github.sha }}

            echo "VALIDATE $DISTRO ******************************************************************"
            echo "ansible-playbook -i examples/inventory-test-${DISTRO}.yml -u root main.yml"
            ansible-playbook -i examples/inventory-test-${DISTRO}.yml -u root main.yml

            echo "!!!SUCCESS!!!"

            echo "Cleanup $DISTRO ******************************************************************"
            echo "ansible-playbook -i examples/inventory-test-${DISTRO}.yml -u root main.yml --tags purge"
            ansible-playbook -i examples/inventory-test-${DISTRO}.yml -u root main.yml --tags purge

          EOF
        env:
          PY_COLORS: "1"
          ANSIBLE_FORCE_COLOR: "1"
          DISTRO: "centos8"

      - name: Debian9
        run: |
          ssh -t -p ${{ secrets.SSH_PORT }} -l ${{ secrets.SSH_USER }} ${{ secrets.SSH_HOST }} <<EOF

            set -e

            export PY_COLORS=1
            export ANSIBLE_FORCE_COLOR=1

            cd ~/${{ github.sha }}

            echo "VALIDATE $DISTRO ******************************************************************"
            echo "ansible-playbook -i examples/inventory-test-${DISTRO}.yml -u root main.yml"
            ansible-playbook -i examples/inventory-test-${DISTRO}.yml -u root main.yml

            echo "!!!SUCCESS!!!"

            echo "Cleanup $DISTRO ******************************************************************"
            echo "ansible-playbook -i examples/inventory-test-${DISTRO}.yml -u root main.yml --tags purge"
            ansible-playbook -i examples/inventory-test-${DISTRO}.yml -u root main.yml --tags purge

          EOF
        env:
          PY_COLORS: "1"
          ANSIBLE_FORCE_COLOR: "1"
          DISTRO: "debian9"

      - name: Debian10
        run: |
          ssh -t -p ${{ secrets.SSH_PORT }} -l ${{ secrets.SSH_USER }} ${{ secrets.SSH_HOST }} <<EOF

            set -e

            export PY_COLORS=1
            export ANSIBLE_FORCE_COLOR=1

            cd ~/${{ github.sha }}

            echo "VALIDATE $DISTRO ******************************************************************"
            echo "ansible-playbook -i examples/inventory-test-${DISTRO}.yml -u root main.yml"
            ansible-playbook -i examples/inventory-test-${DISTRO}.yml -u root main.yml

            echo "!!!SUCCESS!!!"

            echo "Cleanup $DISTRO ******************************************************************"
            echo "ansible-playbook -i examples/inventory-test-${DISTRO}.yml -u root main.yml --tags purge"
            ansible-playbook -i examples/inventory-test-${DISTRO}.yml -u root main.yml --tags purge

          EOF
        env:
          PY_COLORS: "1"
          ANSIBLE_FORCE_COLOR: "1"
          DISTRO: "debian10"

      - name: OpenSUSE
        run: |
          ssh -t -p ${{ secrets.SSH_PORT }} -l ${{ secrets.SSH_USER }} ${{ secrets.SSH_HOST }} <<EOF

            set -e

            export PY_COLORS=1
            export ANSIBLE_FORCE_COLOR=1

            cd ~/${{ github.sha }}

            echo "VALIDATE $DISTRO ******************************************************************"
            echo "ansible-playbook -i examples/inventory-test-${DISTRO}.yml -u root main.yml"
            ansible-playbook -i examples/inventory-test-${DISTRO}.yml -u root main.yml

            echo "!!!SUCCESS!!!"

            echo "Cleanup $DISTRO ******************************************************************"
            echo "ansible-playbook -i examples/inventory-test-${DISTRO}.yml -u root main.yml --tags purge"
            ansible-playbook -i examples/inventory-test-${DISTRO}.yml -u root main.yml --tags purge

          EOF
        env:
          PY_COLORS: "1"
          ANSIBLE_FORCE_COLOR: "1"
          DISTRO: "opensuse15"

      - name: Ubuntu18
        run: |
          ssh -t -p ${{ secrets.SSH_PORT }} -l ${{ secrets.SSH_USER }} ${{ secrets.SSH_HOST }} <<EOF

            set -e

            export PY_COLORS=1
            export ANSIBLE_FORCE_COLOR=1

            cd ~/${{ github.sha }}

            echo "VALIDATE $DISTRO ******************************************************************"
            echo "ansible-playbook -i examples/inventory-test-${DISTRO}.yml -u root main.yml"
            ansible-playbook -i examples/inventory-test-${DISTRO}.yml -u root main.yml

            echo "!!!SUCCESS!!!"

            echo "Cleanup $DISTRO ******************************************************************"
            echo "ansible-playbook -i examples/inventory-test-${DISTRO}.yml -u root main.yml --tags purge"
            ansible-playbook -i examples/inventory-test-${DISTRO}.yml -u root main.yml --tags purge

          EOF
        env:
          PY_COLORS: "1"
          ANSIBLE_FORCE_COLOR: "1"
          DISTRO: "ubuntu18"

      - name: Ubuntu18 (Netplan)
        run: |
          ssh -t -p ${{ secrets.SSH_PORT }} -l ${{ secrets.SSH_USER }} ${{ secrets.SSH_HOST }} <<EOF

            set -e

            export PY_COLORS=1
            export ANSIBLE_FORCE_COLOR=1

            cd ~/${{ github.sha }}

            echo "VALIDATE $DISTRO ******************************************************************"
            echo "ansible-playbook -i examples/inventory-test-${DISTRO}.yml -u root main.yml"
            ansible-playbook -i examples/inventory-test-${DISTRO}.yml -u root main.yml

            echo "!!!SUCCESS!!!"

            echo "Cleanup $DISTRO ******************************************************************"
            echo "ansible-playbook -i examples/inventory-test-${DISTRO}.yml -u root main.yml --tags purge"
            ansible-playbook -i examples/inventory-test-${DISTRO}.yml -u root main.yml --tags purge

          EOF
        env:
          PY_COLORS: "1"
          ANSIBLE_FORCE_COLOR: "1"
          DISTRO: "ubuntu18-netplan"

      - name: Ubuntu20
        run: |
          ssh -t -p ${{ secrets.SSH_PORT }} -l ${{ secrets.SSH_USER }} ${{ secrets.SSH_HOST }} <<EOF

            set -e

            export PY_COLORS=1
            export ANSIBLE_FORCE_COLOR=1

            cd ~/${{ github.sha }}

            echo "VALIDATE $DISTRO ******************************************************************"
            echo "ansible-playbook -i examples/inventory-test-${DISTRO}.yml -u root main.yml"
            ansible-playbook -i examples/inventory-test-${DISTRO}.yml -u root main.yml

            echo "!!!SUCCESS!!!"

            echo "Cleanup $DISTRO ******************************************************************"
            echo "ansible-playbook -i examples/inventory-test-${DISTRO}.yml -u root main.yml --tags purge"
            ansible-playbook -i examples/inventory-test-${DISTRO}.yml -u root main.yml --tags purge

          EOF
        env:
          PY_COLORS: "1"
          ANSIBLE_FORCE_COLOR: "1"
          DISTRO: "ubuntu20"

      - name: Ubuntu20 (Netplan)
        run: |
          ssh -t -p ${{ secrets.SSH_PORT }} -l ${{ secrets.SSH_USER }} ${{ secrets.SSH_HOST }} <<EOF

            set -e

            export PY_COLORS=1
            export ANSIBLE_FORCE_COLOR=1

            cd ~/${{ github.sha }}

            echo "VALIDATE $DISTRO ******************************************************************"
            echo "ansible-playbook -i examples/inventory-test-${DISTRO}.yml -u root main.yml"
            ansible-playbook -i examples/inventory-test-${DISTRO}.yml -u root main.yml

            echo "!!!SUCCESS!!!"

            echo "Cleanup $DISTRO ******************************************************************"
            echo "ansible-playbook -i examples/inventory-test-${DISTRO}.yml -u root main.yml --tags purge"
            ansible-playbook -i examples/inventory-test-${DISTRO}.yml -u root main.yml --tags purge

          EOF
        env:
          PY_COLORS: "1"
          ANSIBLE_FORCE_COLOR: "1"
          DISTRO: "ubuntu20-netplan"

      - name: FreeBSD-12
        run: |
          ssh -t -p ${{ secrets.SSH_PORT }} -l ${{ secrets.SSH_USER }} ${{ secrets.SSH_HOST }} <<EOF

            set -e

            export PY_COLORS=1
            export ANSIBLE_FORCE_COLOR=1

            cd ~/${{ github.sha }}

            echo "VALIDATE $DISTRO ******************************************************************"
            echo "ansible-playbook -i examples/inventory-test-${DISTRO}.yml -u root main.yml"
            ansible-playbook -i examples/inventory-test-${DISTRO}.yml -u root main.yml

            echo "!!!SUCCESS!!!"

            echo "Cleanup $DISTRO ******************************************************************"
            echo "ansible-playbook -i examples/inventory-test-${DISTRO}.yml -u root main.yml --tags purge"
            ansible-playbook -i examples/inventory-test-${DISTRO}.yml -u root main.yml --tags purge

          EOF
        env:
          PY_COLORS: "1"
          ANSIBLE_FORCE_COLOR: "1"
          DISTRO: "freebsd12"

      - name: FreeBSD-13
        run: |
          ssh -t -p ${{ secrets.SSH_PORT }} -l ${{ secrets.SSH_USER }} ${{ secrets.SSH_HOST }} <<EOF

            set -e

            export PY_COLORS=1
            export ANSIBLE_FORCE_COLOR=1

            cd ~/${{ github.sha }}

            echo "VALIDATE $DISTRO ******************************************************************"
            echo "ansible-playbook -i examples/inventory-test-${DISTRO}.yml -u root main.yml"
            ansible-playbook -i examples/inventory-test-${DISTRO}.yml -u root main.yml

            echo "!!!SUCCESS!!!"

            echo "Cleanup $DISTRO ******************************************************************"
            echo "ansible-playbook -i examples/inventory-test-${DISTRO}.yml -u root main.yml --tags purge"
            ansible-playbook -i examples/inventory-test-${DISTRO}.yml -u root main.yml --tags purge

          EOF
        env:
          PY_COLORS: "1"
          ANSIBLE_FORCE_COLOR: "1"
          DISTRO: "freebsd13"

      - name: Cleanup Folder
        run: |
          ssh -p ${{ secrets.SSH_PORT }} -l ${{ secrets.SSH_USER }} ${{ secrets.SSH_HOST }} "rm -rf ~/${{ github.sha }} ~/.ssh/known_hosts ~/.terrible"
