---

name: Docker Build

on:
  push:
    branches: master

jobs:
  main:
    runs-on: ubuntu-latest
    steps:

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_ID }}
          password: ${{ secrets.DOCKER_PSK }}

      - uses: actions/checkout@v2

      - name: Shrink README
        run:  grep -n Compatibility README.md | tail -1 | cut -d":" -f1 | xargs -I{} head -n{} README.md  | head -n-1 > README-DOCKER.md

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v2.4.3
        with:
          username: ${{ secrets.DOCKER_ID }}
          password: ${{ secrets.DOCKER_PSK }}
          repository: 89luca89/terrible
          readme-filepath: ./README-DOCKER.md

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: ./Dockerfile
          push: true
          tags: |
            89luca89/terrible:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
