---

- name: "Setup machine hostname"
  win_hostname:
    name: "{{ inventory_hostname }}"

- name: "Set connection setting files - Windows"
  win_shell: |
    New-NetIpAddress -InterfaceIndex {{ item.0.interface_index }} -IPAddress {{ item.1.ip }} -PrefixLength 24 {% if item.0.default_gateway is not defined %}-DefaultGateway {{ item.1.gw }}{% endif %}
  async: 100
  poll: 0
  with_together:
    - "{{ ansible_facts.interfaces | sort(attribute='connection_name') }}"
    - "{{ network_interfaces.values() | list }}"

- name: "Restart networking - apply configs" # noqa 503
  win_shell: |
    Restart-NetAdapter -InterfaceAlias {{ item.0.connection_name }}
  async: 100
  poll: 0
  with_together:
    - "{{ ansible_facts.interfaces | sort(attribute='connection_name') }}"

...
