---

- name: "Setup machine hostname"
  hostname:
    name: "{{ inventory_hostname }}"

# Gather up all interfaces
- name: get available devices
  shell: |
    set -o pipefail;
    ifconfig -l | sed 's/lo[0-9]//g'| awk '{$1=$1};1'
  changed_when: no
  register: interfaces

- name: "Set connection setting files"
  blockinfile:
    path: "/etc/rc.conf"
    mode: 0644
    block: |
      ifconfig_{{ item.0 }}="inet {{ item.1.ip }} netmask 255.255.255.0"
      {% if item.1.get('default_route', False) %}
      defaultrouter="{{ item.1.gw }}"
      {% endif %}
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item.1.ip }}"
    create: yes
  register: connection_file
  with_together:
    - "{{ interfaces.stdout.split(' ') | sort | list }}"
    - "{{ network_interfaces.values() | list }}"

- name: "Set connection setting files"
  blockinfile:
    path: "/etc/resolv.conf"
    mode: 0644
    block: |
      {% if item.1.get('default_route', False) %}
      nameserver {{ item.1.gw }}
      {% endif %}
      {% for dns in item.1.dns %}
      nameserver {{ dns }}
      {% endfor %}
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item.1.ip }}"
    create: yes
  register: resolv_file
  with_together:
    - "{{ interfaces.stdout.split(' ') | sort | list }}"
    - "{{ network_interfaces.values() | list }}"

- name: "Set connection setting files"
  blockinfile:
    path: "/etc/resolvconf.conf"
    mode: 0644
    block: |
      resolvconf=NO
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
    create: yes
  register: resolvconf_file

- name: "Restart networking - apply configs"  # noqa 503
  command: "/etc/netstart"
  async: 1
  poll: 0
  when: "connection_file.changed or resolv_file.changed or resolvconf_file.changed"
